import Figma from '../../../assets/figma.svg'
import Notion from '../../../assets/notion.png'
import Airtable from '../../../assets/airtable.png'
import Office from '../../../assets/office.png'
import Sheets from '../../../assets/sheets.png'
const templates = [
  {
    type: 'figma',
    caption: 'Onboarding form for clients',
    content: 'template for onboarding, template for onboarding',
    logo: Figma,
    typeColor: 'rgba(25, 188, 254, 0.11)',
    likes: '20',
    contributor: 'kingsley',
    link: 'https://aorthar.com/bootcamp',
    tags: ['design', 'clients', 'templates'],
  },
  {
    type: 'figma',
    caption: 'Onboarding form for clients',
    content: 'template for onboarding, template for onboarding',
    logo: Figma,
    typeColor: 'rgba(25, 188, 254, 0.11)',
    likes: '20',
    contributor: 'kingsley',
    link: 'https://aorthar.com/bootcamp',
    tags: ['design', 'clients', 'templates'],
  },
  {
    type: 'figma',
    caption: 'Onboarding form for clients',
    content: 'template for onboarding, template for onboarding',
    logo: Figma,
    typeColor: 'rgba(25, 188, 254, 0.11)',
    likes: '20',
    contributor: 'kingsley',
    link: 'https://aorthar.com/bootcamp',
    tags: ['design', 'clients', 'templates'],
  },
  {
    type: 'figma',
    caption: 'Onboarding form for clients',
    content: 'template for onboarding, template for onboarding',
    logo: Figma,
    typeColor: 'rgba(25, 188, 254, 0.11)',
    likes: '20',
    contributor: 'kingsley',
    link: 'https://aorthar.com/bootcamp',
    tags: ['design', 'clients', 'templates'],
  },
  {
    type: 'figma',
    caption: 'Onboarding form for clients',
    content: 'template for onboarding, template for onboarding',
    logo: Figma,
    typeColor: 'rgba(25, 188, 254, 0.11)',
    likes: '20',
    contributor: 'kingsley',
    link: 'https://aorthar.com/bootcamp',
    tags: ['design', 'clients', 'templates'],
  },
  {
    type: 'figma',
    caption: 'Onboarding form for clients',
    content: 'template for onboarding, template for onboarding',
    logo: Figma,
    typeColor: 'rgba(25, 188, 254, 0.11)',
    likes: '20',
    contributor: 'kingsley',
    link: 'https://aorthar.com/bootcamp',
    tags: ['design', 'clients', 'templates'],
  },
  {
    type: 'figma',
    caption: 'Onboarding form for clients',
    content: 'template for onboarding, template for onboarding',
    logo: Figma,
    typeColor: 'rgba(25, 188, 254, 0.11)',
    likes: '20',
    contributor: 'kingsley',
    link: 'https://aorthar.com/bootcamp',
    tags: ['design', 'clients', 'templates'],
  },
  {
    type: 'figma',
    caption: 'Onboarding form for clients',
    content: 'template for onboarding, template for onboarding',
    logo: Figma,
    typeColor: 'rgba(25, 188, 254, 0.11)',
    likes: '20',
    contributor: 'kingsley',
    link: 'https://aorthar.com/bootcamp',
    tags: ['design', 'clients', 'templates'],
  },
  {
    type: 'figma',
    caption: 'Onboarding form for clients',
    content: 'template for onboarding, template for onboarding',
    logo: Figma,
    typeColor: 'rgba(25, 188, 254, 0.11)',
    likes: '20',
    contributor: 'kingsley',
    link: 'https://aorthar.com/bootcamp',
    tags: ['design', 'clients', 'templates'],
  },
  {
    type: 'mircorosft-word',
    caption: 'Onboarding form for clients',
    content: 'template for onboarding, template for onboarding',
    logo: Office,
    typeColor: '#E6EDFF',
    likes: '20',
    contributor: 'kingsley',
    link: 'https://aorthar.com/bootcamp',
    tags: ['design', 'clients', 'templates'],
  },
  {
    type: 'figma',
    caption: 'Onboarding form for clients',
    content: 'template for onboarding, template for onboarding',
    logo: Figma,
    typeColor: 'rgba(25, 188, 254, 0.11)',
    likes: '20',
    contributor: 'kingsley',
    link: 'https://aorthar.com/bootcamp',
    tags: ['design', 'clients', 'templates'],
  },
  {
    type: 'figma',
    caption: 'Onboarding form for clients',
    content: 'template for onboarding, template for onboarding',
    logo: Figma,
    typeColor: 'rgba(25, 188, 254, 0.11)',
    likes: '20',
    contributor: 'kingsley',
    link: 'https://aorthar.com/bootcamp',
    tags: ['design', 'clients', 'templates'],
  },
  {
    type: 'airtable',
    caption: 'Onboarding form for clients',
    content: 'template for onboarding, template for onboarding',
    logo: Airtable,
    typeColor: ' #FFE8E6',
    likes: '20',
    contributor: 'kingsley',
    link: 'https://aorthar.com/bootcamp',
    tags: ['design', 'clients', 'templates'],
  },
  {
    type: 'figma',
    caption: 'Onboarding form for clients',
    content: 'template for onboarding, template for onboarding',
    logo: Figma,
    typeColor: 'rgba(25, 188, 254, 0.11)',
    likes: '20',
    contributor: 'kingsley',
    link: 'https://aorthar.com/bootcamp',
    tags: ['design', 'clients', 'templates'],
  },
  {
    type: 'Notion',
    caption: 'Onboarding form for clients',
    content: 'template for onboarding, template for onboarding',
    logo: Notion,
    typeColor: '#FFF5E6',
    likes: '20',
    contributor: 'kingsley',
    link: 'https://aorthar.com/bootcamp',
    tags: ['design', 'clients'],
  },
  {
    type: 'Google Sheets',
    caption: 'Onboarding form for clients',
    content: 'template for onboarding, template for onboarding',
    logo: Sheets,
    typeColor: ' #E8FFE6',
    likes: '20',
    contributor: 'kingsley',
    link: 'https://aorthar.com/bootcamp',
    tags: ['design', 'clients', 'templates'],
  },
]

export default templates
